[package]
name = "power_k8s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
podman-api = "0.8.0"
tokio = { version = "1", features = ["full"] }
