apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{.Release.Namespace}}
  name: install-addons
  labels:
    app: vela-cli
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: install-addon
      labels:
        app: vela-cli
    spec:
      containers:
        - name: install
          image: {{ .Values.image.addons }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
      restartPolicy: OnFailure
      serviceAccountName: kubevela-vela-core
