apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
  namespace: {{.Release.Namespace}}
data:
{{/*  image: gcr.io/cf-build-service-public/kpack/build-init@sha256:28b9ec694ac655b16c5be8a9fed989b6798c03db22624212c8cd259567482b4d*/}}
  image: {{.Values.images.registry}}/cf-build-service-public/kpack/build-init:0.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
  namespace: {{.Release.Namespace}}
data:
{{/*  image: gcr.io/cf-build-service-public/kpack/build-init-windows@sha256:e89df4c3cc17e649a1bf7ebbf69f339423d1fb44fcd436ddca11e28fd703e2d8*/}}
  image: {{.Values.images.registry}}/cf-build-service-public/kpack/build-init-windows:0.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-waiter-image
  namespace: {{.Release.Namespace}}
data:
{{/*  image: gcr.io/cf-build-service-public/kpack/build-waiter@sha256:b4eeb2c6047b963ebb54da39c20a179c49a105bd6dc08b5ac99563fe9b1e7b24*/}}
  image: {{.Values.images.registry}}/cf-build-service-public/kpack/build-waiter:0.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
  namespace: {{.Release.Namespace}}
data:
{{/*  image: gcr.io/cf-build-service-public/kpack/rebase@sha256:d7486624ac190a0365f9107d36584a30ffac9e234e8beba6c0b16b164041f982*/}}
  image: {{.Values.images.registry}}/cf-build-service-public/kpack/rebase:0.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
  namespace: {{.Release.Namespace}}
data:
{{/*  image: gcr.io/cf-build-service-public/kpack/lifecycle@sha256:284a738d402060ffd196bf65c4ad1177dbf24278207bee09037eeab613653b2f*/}}
  image: {{.Values.images.registry}}/cf-build-service-public/kpack/lifecycle:0.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
  namespace: {{.Release.Namespace}}
data:
{{/*  image: gcr.io/cf-build-service-public/kpack/completion@sha256:c07d52bd05cf8b610443d615cb0324accd44cecfa644e2133130eedffaaf92d0*/}}
  image: {{.Values.images.registry}}/cf-build-service-public/kpack/completion:0.9.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
  namespace: {{.Release.Namespace}}
data:
{{/*  image: gcr.io/cf-build-service-public/kpack/completion-windows@sha256:9020eebf7247d8ed08a95e230c5f8129dbaa7d141a0dd7da9a7fb73c7c68d8cc*/}}
  image: {{.Values.images.registry}}/cf-build-service-public/kpack/completion-windows:0.9.2
