root = "/data/containerd"

[plugins."io.containerd.grpc.v1.cri"]
systemd_cgroup = true
sandbox_image = "k8s.gcr.io/pause:3.6"


[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/etc/containerd/certs.d"
