root = "/data/containerd"

[plugins."io.containerd.grpc.v1.cri"]
systemd_cgroup = true
sandbox_image = "registry.powerk8s.cn/pause:3.8"


[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/etc/containerd/certs.d"
