apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-webhook-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    component: controller
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}